version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1224
      MYSQL_DATABASE: airaware
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    depends_on:
      - api
      - db
    ports:
      - "8501:8501"
    env_file:
      - .env

volumes:
  mysql_data:
